### ISSUE TITLE
At time the plugin logs: [Alert] Graylog alert for stream: <streamname>

### ISSUE THREAD

**Issue by 123dev** [magicdude4eva/graylog-jira-alarmcallback#11] opened 2016-05-24 18:39 UTC
Hi Gerd,

Not sure if this has happened with you at all, every now and then the plugin logs a blank message, as if it had to data to work with (last message perhaps?)

All the fields logged are similar to a test  ticket.
So instead of the actual field values, we get the field name variables.

Could there be a timing issue that the alert is triggered but the plugin still doesn't know about the last message, and hence logs the default values?

Thanks

**Comment by magicdude4eva** [comment] 2016-05-25 06:18
Hi there,

this has never happened to me. The only time something like this would occur is if an alert is triggered, but it does not contain a last-message.

When Graylog triggers the alert it is supposed to attach a last-message if it has one and in your case it looks like it triggered the alert but did not include the message.

Perhaps an issue with Graylog itself? I have been running Graylog 2.0.1 for the last 4 weeks and have not experienced any issues. If you are able to upgrade, I would recommend it, as it gets rid of the separate webserver (but be aware that it has an ElasticSearch dependency - in my case I just dropped all messages in ES and started fresh).

**Comment by 123dev** [comment] 2016-05-25 15:17
Thanks Gerd,

We have on our plans to upgrade to Graylog 2.0.1
However it is not as straight forward as we want it, specially for AWS images, where we want to just upgrade and not lose anything. (clustered environment, lots of configuration, we even setup a new 2.0.0 instance and trying exporting content_packs and importing them to the new instance, just to test how it would go, some things worked, others broke)

You can close this ticket, once we upgrade and still experience this issue, I'll update the ticket.

Thanks

**Comment by magicdude4eva** [comment] 2016-05-25 18:19
No problem - good luck with the upgrade.

**Comment by 123dev** [comment] 2016-06-17 19:46
Hi Gerd,
Hope you're doing well.

We upgraded to Graylog 2.0.2 and again experienced this issue today.

In jira I saw a ticket logged, with all the fields at their default value (test condition)
example:
**elapsed_time_ms**: [LAST_MESSAGE.elapsed_time_ms]

as if the plugin did not know anything about the message, but got triggered.

I checked the timestamp of Jira ticket creation and it was
Created:	Today 12:52 PM

Then I checked the stream messages and Found an entry
2016-06-17 12:51:42.896

Which I assumed to be the trigger message.

One thing to point out is that we are running two graylog-servers and four datanodes total
not sure if that makes a difference.

Thanks again for all your help.

**Comment by magicdude4eva** [comment] 2016-06-18 04:33
Hi there - could you perhaps include all log-records from Graylog during the time the message was processed?

Looking at code (`buildDescription`), it would only do this if Graylog did not provide a message:
```
    // Get the last message
    if (!result.getMatchingMessages().isEmpty()) {
      // get fields from last message only
      MessageSummary lastMessage = result.getMatchingMessages().get(0);
      ....
```

I have never seen this and the only explanation I might have is that Graylog triggered the alert but then failed to include a message. Perhaps log-records before / after the event will highlight the actual cause.

I assume that other tickets are logged correctly (if not, then perhaps there is an issue with a trigger condition). Another reason could be if you have multiple alerts for the same trigger and somehow this causes a race-condition.

**Comment by 123dev** [comment] 2016-06-18 14:22
Hi Gerd,

You're right again
Looking at graylog logs around the time this issue happened I see this log entry

```
2016-06-17_16:52:04.15041 2016-06-17 16:52:04,149 WARN : com.bidorbuy.graylog.alarmcallbacks.jira.JiraAlarmCallback - Skipping JIRA-issue MD5 generation, alarmcallback did not provide a message
2016-06-17_16:52:06.49685 2016-06-17 16:52:06,495 INFO : com.bidorbuy.graylog.alarmcallbacks.jira.JiraAlarmCallback - Created new issue API-570 for project API
```

So this looks like a bug in Graylog?
In these cases, can you skip logging an empty Jira ticket?
Perhaps log a Graylog alert, similar to the red number appears in the dashboard when there are updates or input is down ... (I don't know if you even have that power in a plugin)

From usability perspective, we want to know that this happened but don't want a useless ticket in Jira.

Thanks again.

**Comment by magicdude4eva** [comment] 2016-06-18 14:36
Hi there, could you possibly log a ticket with Graylog via https://github.com/Graylog2/graylog2-server? 

I initially thought about skipping logging a ticket if a message is not present, but then decided against it, as there might be a very good reason (i.e. a bug in Graylog or a misconfiguration of the alarm callback trigger) that a message was skipped.

Graylog does not allow detailed logging - i.e. you will notice the "Triggered Alerts" table will only include some summary of triggered alerts, but no detail of what the cause was. I somehow tend to think that maybe your alert configuration is "too complex" that it prevents Graylog from providing a backlog (i.e. too many stream alerts being fired and Graylog does retain the message) - the only time I have seen this is if the trigger has a long duration (i.e. "trigger when more than 4 alerts in the last 600 minutes"). All the conditions we have configured are less than 30 minutes. Just to make sure: You do have it configured with "When sending an alert, include the last 1 messages of the stream evaluated for this alert condition."?

In the worst case I would include a flag "Skip logging tickets if alarmcallback does not provide a message", but I would prefer to get to the bottom of it. Perhaps there is more detail prior to firing the AlarmCallback in the Graylog log?

**Comment by 123dev** [comment] 2016-06-18 14:45
Hi Gerd,

Here's our Alert condition, I doubt that it's causing the problem, but let me know if you think it might
![2016-06-18 10_41_21-graylog web interface](https://cloud.githubusercontent.com/assets/13109154/16171623/700e3962-3541-11e6-89bf-3f2c432551b1.png)

And this screenshots shows that not much else was happening at the time of this issue
![2016-06-18 09_56_17-graylog web interface](https://cloud.githubusercontent.com/assets/13109154/16171626/8c85f1ac-3541-11e6-81c3-186cb28307df.png)

I will log a ticket with Graylog and link it here when done.

I suspect this is a graylog bug and not much you can do if you didn't get a message
but this would be great until they fix it in Graylog

> In the worst case I would include a flag "Skip logging tickets if alarmcallback does not provide a message",

Thanks again

**Comment by magicdude4eva** [comment] 2016-06-18 15:02
I initially thought that perhaps you have a short timespan as a condition with too many messages possibly flushing out the backlog, but does not seem the case.

I would perhaps rework your alert condition to something where you define a limit of how many messages you would accept before triggering an alert. In our case we trigger an alert if we receive more than 5 messages in the last 30 minutes and have no grace period - i.e. if we get 5 messages in 30 minutes, we log a ticket.

In your case you might want to look at "more than 2 messages in 120 minutes and then wait at least 0 minutes..." - this might not be acceptable if you have an incident team / SLA which requires quicker response.

I would certainly log a Graylog issue as well.

**Comment by 123dev** [comment] 2016-06-18 15:09
Thanks Gerd

Ticket [logged](https://github.com/Graylog2/graylog2-server/issues/2382)

Yeah, we want to be notified as soon as the problem occurs, not only that, each message potentially is a unique new ticket and we want a ticket for each and not one for the last two.

Thanks for all your support.

**Comment by kroepke** [comment] 2016-06-20 10:14
@123dev @magicdude4eva Thanks for the heads up!

This particular issue arises with the message count alert condition, as described in https://github.com/Graylog2/graylog2-server/issues/2382#issuecomment-227099715

I've also created https://github.com/Graylog2/graylog2-server/issues/2387 for 2.1.0 to fix the problem.

From this perspective I think you can close this issue, because it appears that Graylog does not hand you the message if it just slips out of the time range (when it is evaluated for the second time).

**Comment by magicdude4eva** [comment] 2016-06-20 11:27
This is great. Thanks @123dev and @kroepke for pinpointing the issue.

**Closed by magicdude4eva** 2016-06-20 11:27 UTC

**Comment by 123dev** [comment] 2017-02-23 18:09
Not sure why, I'm still getting this issue with the
Latest plugin 1.0.8
and Latest Graylog 2.2.1

I see the following in my logs.
```2017-02-23_15:59:12.53933 2017-02-23 15:59:12,538 WARN : com.bidorbuy.graylog.alarmcallbacks.jira.JiraAlarmCallback - Skipping JIRA-issue MD5 generation, alarmcallback did not provide a message
2017-02-23_15:59:15.38832 2017-02-23 15:59:15,387 INFO : com.bidorbuy.graylog.alarmcallbacks.jira.JiraAlarmCallback - Created new issue API-1010 for project API
```

I know not getting the message is a Graylog bug, but perhaps the plugin can be improved not to create an empty jira ticket and just log in graylog logs or if possible raise an alert.

**Comment by 123dev** [comment] 2017-10-05 16:47
Update:

This issue is still happening with Graylog 2.3.1
However I can assure that this is not a plugin bug, but rather Graylog issue.
I have multiple notification plugins setup, and when the problem occurs, both Jira plugin and slack plugin get no message.

**Comment by 123dev** [comment] 2017-10-05 16:51
Gerd,

It would be nice if the plugin if it encounters this situation (ie no message received) that it doesn't forward / create a jira ticket.
Ideally Graylog should fix this, but in the absence of it, it helps keeping Jira tidy.

Thanks

**Comment by magicdude4eva** [comment] 2017-10-06 06:21
I prefer not to reject/drop an alert if the message is empty. From a JIRA plugin perspective there could be other reasons why a message is empty (i.e. a user configures a REGEX wrong).

I have not noticed these issues on my end.

FWIW - we are now also using [Automation for JIRA](https://codebarrel.atlassian.net/wiki/spaces/AUTO4J/overview) which allows us to further route any tickets. For example, we do get some "noisy" tickets coming through where we know that those should be dropped.

**Comment by 123dev** [comment] 2017-10-10 14:08
Thanks Gerd,
I fully understand your position, I'll take a look at Automation for Jira to see if that can help us.
